# Fashion Mnist Classification

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/dgaida/wpf_dlml_th_public/blob/main/assets/exercises/week_05/07_fashion_mnist_classification.ipynb)

This notebook contains an exercise from the Deep Learning, Machine Learning, and AI course.

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

# 1. Fashion MNIST Datensatz laden
fashion_mnist = keras.datasets.fashion_mnist
(x_train_full, y_train_full), (x_test, y_test) = fashion_mnist.load_data()

# 2. Validierungsset erstellen (erste 5000 Datenpunkte) und Normalisierung
# Das Validierungsset wird zur Überwachung der Genauigkeit während des Trainings verwendet.
x_valid, x_train = x_train_full[:5000] / 255.0, x_train_full[5000:] / 255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]
x_test = x_test / 255.0

# 3. Shape und Dtype des Trainingssets ausgeben
print(f"Shape des Trainingssets: {x_train.shape}")
print(f"Dtype des Trainingssets: {x_train.dtype}")

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
Shape des Trainingssets: (55000, 28, 28)
Dtype des Trainingssets: float64


In [2]:
# 4. Modell erstellen (wie im bereitgestellten Bild)
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dense(300, activation="relu"),
    keras.layers.Dense(100, activation="relu"),
    keras.layers.Dense(10, activation="softmax")
])

# 5. Modellzusammenfassung ausgeben
print(model.summary())

# 6. Modell kompilieren (mit Adam-Optimizer für bessere Performance)
model.compile(loss="sparse_categorical_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 266,610 (1.02 MB)

 Trainable params: 266,610 (1.02 MB)

 Non-trainable params: 0 (0.00 B)

None


In [3]:
# 7. Modell trainieren
# Während des Trainings wird die Genauigkeit des Validierungssets (val_accuracy) angezeigt.
history = model.fit(x_train, y_train, epochs=10,
                    validation_data=(x_valid, y_valid))

Epoch 1/10
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8249 - loss: 0.4838 - val_accuracy: 0.8678 - val_loss: 0.3764
Epoch 2/10
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8671 - loss: 0.3612 - val_accuracy: 0.8752 - val_loss: 0.3377
Epoch 3/10
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8803 - loss: 0.3268 - val_accuracy: 0.8830 - val_loss: 0.3218
Epoch 4/10
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8888 - loss: 0.3005 - val_accuracy: 0.8882 - val_loss: 0.3178
Epoch 5/10
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8931 - loss: 0.2857 - val_accuracy: 0.8890 - val_loss: 0.3121
Epoch 6/10
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8988 - loss: 0.2712 - val_accuracy: 0.8956 - val_loss: 0.3031
Epoch 7/10
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9034 - loss: 0.2573 - val_accuracy: 0.8888 - val_loss: 0.2911
Epoch 8/10
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9075 - loss: 0.2466 - 

In [4]:
# 8. Evaluierung auf dem Testdatensatz
print("\nEvaluierung auf dem Testdatensatz:")
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test-Genauigkeit: {test_acc}")


Evaluierung auf dem Testdatensatz:
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8873 - loss: 0.3326
Test-Genauigkeit: 0.8873000144958496


In [5]:
# 9. Vorhersagen für die ersten 3 Datenpunkte des Testsets
x_new = x_test[:3]

# predict aufrufen
y_proba = model.predict(x_new)
print("\nVorhersagewahrscheinlichkeiten (predict):")
print(y_proba.round(2))

# predict_classes aufrufen
# Hinweis: predict_classes ist in neueren TensorFlow-Versionen entfernt.
# Wir verwenden np.argmax als direkten Ersatz.
try:
    y_pred = model.predict_classes(x_new)
    print("\nVorhergesagte Klassen (predict_classes):")
except AttributeError:
    y_pred = np.argmax(model.predict(x_new), axis=-1)
    print("\nVorhergesagte Klassen (Ersatz für predict_classes):")

print(y_pred)
print("Tatsächliche Klassen:")
print(y_test[:3])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 487ms/step

Vorhersagewahrscheinlichkeiten (predict):
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

Vorhergesagte Klassen (Ersatz für predict_classes):
[9 2 1]
Tatsächliche Klassen:
[9 2 1]


In [ ]:
import matplotlib.pyplot as plt

# Klassennamen für Fashion MNIST auf Deutsch
class_names = ["T-Shirt/Top", "Hose", "Pullover", "Kleid", "Mantel",
               "Sandale", "Shirt", "Sneaker", "Tasche", "Stiefelette"]

plt.figure(figsize=(10, 4))
for i in range(3):
    plt.subplot(1, 3, i + 1)
    plt.imshow(x_new[i], cmap="binary")
    plt.axis('off')
    plt.title(f"Vorhergesagt: {class_names[y_pred[i]]}\nIst: {class_names[y_test[i]]}")
plt.show()